OKE-33097- Lustre Release 3 upgarding lustre version to 2.15.5 manifests for AGA region

diff --git a/manifests/lustre-csi-driver/AGA/1.27/Rollback/oci-lustre-csi-cm.yaml b/manifests/lustre-csi-driver/AGA/1.27/Rollback/oci-lustre-csi-cm.yaml
--- a/manifests/lustre-csi-driver/AGA/1.27/Rollback/oci-lustre-csi-cm.yaml
+++ b/manifests/lustre-csi-driver/AGA/1.27/Rollback/oci-lustre-csi-cm.yaml
@@ -21,9 +21,27 @@ data:
         echo "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ") - $1"
     }
     export SYSTEMCTL_FORCE_BUS=1
-    #pre requisite for building lustre packages
-    echo "Installing linux headers"
+
+    # Remove Lustre modules, wait for some time for the modules to be removed
+    retry=0
+    while which lustre_rmmod  && ! lustre_rmmod && [ $retry -lt 10 ]
+    do
+        log "Failed to unload Lustre modules, retry=$retry"
+        sleep 30
+        retry=$((retry+1))
+    done
+
+    if [ $retry -eq 10 ]; then
+        log "Failed to unload Lustre modules after 5 minutes, this node likely require a reboot"
+        exit 1
+    fi
+    log "Successfully unloaded Lustre modules, proceeding with Lustre client installation/upgrade"
+
+    log "Removing existing lustre packages"
     apt-get remove --purge -y lustre-client-modules-dkms || true
+    apt-get remove --purge -y lustre-client-utils || true
+    #pre requisite for building lustre packages
+    log "Installing linux headers"
     dpkg --configure -a
     apt-get update
     apt-get install -y --no-upgrade linux-headers-oracle
