testing

diff --git a/build-scripts/ccm_e2e_spec.yaml b/build-scripts/ccm_e2e_spec.yaml
--- a/build-scripts/ccm_e2e_spec.yaml
+++ b/build-scripts/ccm_e2e_spec.yaml
@@ -33,63 +33,65 @@ steps:
       echo "Printing Disk usage: `df -h`"
       echo "TMPDIR: ${TMPDIR}"
       echo "DOCKER_CONFIG_DIR: ${DOCKER_CONFIG_DIR}"
+      ls -lh
+      ls -lh /oci-cloud-controller-manager-e2e/
     failImmediatelyOnError: true
     timeoutInSeconds: 300
 
-  - type: shell
-    name: Pre Test Cleanup
-    command: |
-      docker rm -f ccm-e2e-test
-      rm -rf ${HOME_LOC}/ccm_e2e
-      mkdir -p ${HOME_LOC}/ccm_e2e || exit
-      echo "Cleaning up working directory"
-    failImmediatelyOnError: false
-    timeoutInSeconds: 600
-
-  - type: shell
-    name: Get CCM Repo
-    command: |
-      cd ccm_e2e
-      git clone ssh://git@bitbucket.oci.oraclecorp.com:7999/oke/oci-cloud-controller-manager.git || exit
-      cd oci-cloud-controller-manager/ || exit
-      git checkout ${E2E_BRANCH} || exit
-      git status
-    failImmediatelyOnError: true
-    timeoutInSeconds: 1200
-
-  - type: shell
-    name: Start Docker-in-Docker
-    command: |
-      mkdir -p ${TMPDIR} ${DOCKER_CONFIG_DIR}
-      cd ${TMPDIR} && pwd
-      cd ${DOCKER_CONFIG_DIR} && pwd
-      [[ $(docker ps -f "name=$DIND_NAME" --format '{{.Names}}') == $DIND_NAME ]] || docker --config $DOCKER_CONFIG_DIR run -t --privileged --net=host -v $DOCKER_CONFIG_DIR:/root/.docker -v $TMPDIR:/var/lib/docker --name $DIND_NAME -d iad.ocir.io/odx-oke/oke/dind:0.2.0
-      docker ps -a
-    failImmediatelyOnError: true
-    timeoutInSeconds: 600
-    onFailure:
-      - type: shell
-        command: |
-          docker rm -f ccm-e2e-test
-          sudo rm -rf ${HOME_LOC}/ccm_e2e
-        timeoutInSeconds: 400
-
-  - type: shell
-    name: Run test
-    command: |
-      echo "Running CCM E2E Test"
-      cd ${TMPDIR} && pwd
-      cd ${DOCKER_CONFIG_DIR} && pwd
-      cd /opt/tssagent/workspace/ccm_e2e/oci-cloud-controller-manager
-      export env_file=$(mktemp)
-      unset OCI_RESOURCE_PRINCIPAL_PRIVATE_PEM
-      env > $env_file
-      ./run_dind.sh run-ccm-e2e-tests-local
-    failImmediatelyOnError: true
-    timeoutInSeconds: 3600
-    onFailure:
-      - type: shell
-        command: |
-          docker rm -f ccm-e2e-test
-          sudo rm -rf ${HOME_LOC}/ccm_e2e
-        timeoutInSeconds: 400
+#  - type: shell
+#    name: Pre Test Cleanup
+#    command: |
+#      docker rm -f ccm-e2e-test
+#      rm -rf ${HOME_LOC}/ccm_e2e
+#      mkdir -p ${HOME_LOC}/ccm_e2e || exit
+#      echo "Cleaning up working directory"
+#    failImmediatelyOnError: false
+#    timeoutInSeconds: 600
+#
+#  - type: shell
+#    name: Get CCM Repo
+#    command: |
+#      cd ccm_e2e
+#      git clone ssh://git@bitbucket.oci.oraclecorp.com:7999/oke/oci-cloud-controller-manager.git || exit
+#      cd oci-cloud-controller-manager/ || exit
+#      git checkout ${E2E_BRANCH} || exit
+#      git status
+#    failImmediatelyOnError: true
+#    timeoutInSeconds: 1200
+#
+#  - type: shell
+#    name: Start Docker-in-Docker
+#    command: |
+#      mkdir -p ${TMPDIR} ${DOCKER_CONFIG_DIR}
+#      cd ${TMPDIR} && pwd
+#      cd ${DOCKER_CONFIG_DIR} && pwd
+#      [[ $(docker ps -f "name=$DIND_NAME" --format '{{.Names}}') == $DIND_NAME ]] || docker --config $DOCKER_CONFIG_DIR run -t --privileged --net=host -v $DOCKER_CONFIG_DIR:/root/.docker -v $TMPDIR:/var/lib/docker --name $DIND_NAME -d iad.ocir.io/odx-oke/oke/dind:0.2.0
+#      docker ps -a
+#    failImmediatelyOnError: true
+#    timeoutInSeconds: 600
+#    onFailure:
+#      - type: shell
+#        command: |
+#          docker rm -f ccm-e2e-test
+#          sudo rm -rf ${HOME_LOC}/ccm_e2e
+#        timeoutInSeconds: 400
+#
+#  - type: shell
+#    name: Run test
+#    command: |
+#      echo "Running CCM E2E Test"
+#      cd ${TMPDIR} && pwd
+#      cd ${DOCKER_CONFIG_DIR} && pwd
+#      cd /opt/tssagent/workspace/ccm_e2e/oci-cloud-controller-manager
+#      export env_file=$(mktemp)
+#      unset OCI_RESOURCE_PRINCIPAL_PRIVATE_PEM
+#      env > $env_file
+#      ./run_dind.sh run-ccm-e2e-tests-local
+#    failImmediatelyOnError: true
+#    timeoutInSeconds: 3600
+#    onFailure:
+#      - type: shell
+#        command: |
+#          docker rm -f ccm-e2e-test
+#          sudo rm -rf ${HOME_LOC}/ccm_e2e
+#        timeoutInSeconds: 400
